export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
// export const TOGGLE_REGISTRATION_DIALOG = "TOGGLE_REGISTRATION_DIALOG";
export const REGISTRATION_DIALOG_OPEN = "REGISTRATION_DIALOG_OPEN";
export const REGISTRATION_DIALOG_CLOSE = "REGISTRATION_DIALOG_CLOSE";

export const TOGGLE_LOADING = "TOGGLE_LOADING";

export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const REQUESTS_PAGE = "REQUESTS_PAGE";
export const SEARCH_USERS_PAGE = "SEARCH_USERS_PAGE";
export const PROFILE_PAGE = "PROFILE_PAGE";
export const DISCUSSION_PAGE = "DISCUSSION_PAGE";
